[tools]
maven = "3"

[env]
_.file = ".env"

[tasks.build]
description = "Build the Project Image"
run = "mvn clean package -DskipTests"

[tasks.run]
description = "Run Spring App"
run = "mvn clean spring-boot:run -Dspring-boot.run.arguments='--server.port={{arg(i=0, default=\"8000\")}}'"

[tasks.docker_run]
description = "Run Docker Compose Project"
run = "docker compose up --build -d"

[tasks.docker_stop]
description = "Stop Docker Compose Project"
run = "docker compose down"

[tasks.postgres_up]
hide = true
run = "docker compose up -d postgres"

[tasks.postgres_down]
hide = true
run = "docker compose down postgres"

[tasks.documentation]
hide = true
description = "Run Documentation File"
dir = "documentation"
run = "uv run zensical serve"
